version: '3'

services:

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
    volumes:
      - type: bind
        source: ./grafana.ini
        target: /etc/grafana/grafana.ini
        read_only: true
      - type: volume
        source: grafanavol
        target: /var/lib/grafana
    depends_on:
      - influxdb
    networks:
      - grafana

  chronograf:
    image: chronograf:latest
    ports:
      - '127.0.0.1:8888:8888'
    volumes:
      - chronovol:/var/lib/chronograf
    depends_on:
      - influxdb
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_USERNAME=${INFLUXDB_USERNAME}
      - INFLUXDB_PASSWORD=${INFLUXDB_PASSWORD}
    networks:
      - grafana

  influxdb:
    image: influxdb:latest
    ports:
      - '8086:8086'
    volumes:
      - influxvol:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=db0
      - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}
    networks:
      - grafana

volumes:
  grafanavol:
  influxvol:
  chronovol:

networks:
  grafana: